package migration

import "fmt"

// Operation is a single change in a migration file — equivalent to Django's Operation base class.
type Operation interface {
	// Description returns a human-readable line shown during migrate (e.g. "Create model Post").
	Description() string

	// SQL returns the forward SQL statements for this operation given a dialect.
	SQL(dialect string) []string

	// RollbackSQL returns the reverse SQL statements.
	RollbackSQL(dialect string) []string

	// AppLabel is the app this operation belongs to.
	AppLabel() string

	// ModelName returns the model name this operation targets (empty if not model-specific).
	ModelName() string
}

// FieldDef describes a single column in a CreateModel operation — mirrors Django's field tuples.
type FieldDef struct {
	Name       string
	ColumnName string
	Type       string // Go ORM type name e.g. "CharField", "IntegerField"
	MaxSize    int    // for varchar
	Null       bool
	Blank      bool
	Unique     bool
	PrimaryKey bool
	AutoIncr   bool
	Default    string // string representation of default value, empty = no default
	Digits     int    // DecimalField precision
	Decimals   int    // DecimalField scale
	RelTable   string // FK target table
	Index      bool
}

// CreateModel is the operation generated by makemigrations for a new model.
// Equivalent to Django's migrations.CreateModel.
type CreateModel struct {
	App    string
	Name   string
	Table  string
	Fields []FieldDef
}

func (op *CreateModel) AppLabel() string  { return op.App }
func (op *CreateModel) ModelName() string { return op.Name }
func (op *CreateModel) Description() string {
	return fmt.Sprintf("Create model %s", op.Name)
}

func (op *CreateModel) SQL(dialect string) []string {
	q := dialectQuote(dialect)
	cols := make([]string, 0, len(op.Fields))
	indexes := []string{}

	for _, f := range op.Fields {
		col := fmt.Sprintf("    %s%s%s %s", q, f.ColumnName, q, fieldSQL(f, dialect))

		if !f.Null && !f.AutoIncr && !f.PrimaryKey {
			col += " NOT NULL"
		}
		if f.Unique && !f.PrimaryKey {
			col += " UNIQUE"
		}
		if f.Default != "" {
			col += fmt.Sprintf(" DEFAULT %s", f.Default)
		}
		cols = append(cols, col)

		if f.Index && !f.Unique && !f.PrimaryKey {
			idxName := fmt.Sprintf("%s_%s", op.Table, f.ColumnName)
			indexes = append(indexes,
				fmt.Sprintf("CREATE INDEX %s%s%s ON %s%s%s (%s%s%s);",
					q, idxName, q, q, op.Table, q, q, f.ColumnName, q))
		}
	}

	createSQL := fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s%s%s (\n%s\n)",
		q, op.Table, q, joinLines(cols))

	if dialect == "mysql" {
		createSQL += " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
	}
	createSQL += ";"

	stmts := []string{createSQL}
	stmts = append(stmts, indexes...)
	return stmts
}

func (op *CreateModel) RollbackSQL(dialect string) []string {
	q := dialectQuote(dialect)
	return []string{fmt.Sprintf("DROP TABLE IF EXISTS %s%s%s;", q, op.Table, q)}
}

// AddField adds a column to an existing table.
// Equivalent to Django's migrations.AddField.
type AddField struct {
	App   string
	Model string
	Table string
	Field FieldDef
}

func (op *AddField) AppLabel() string  { return op.App }
func (op *AddField) ModelName() string { return op.Model }
func (op *AddField) Description() string {
	return fmt.Sprintf("Add field %s to %s", op.Field.Name, op.Model)
}

func (op *AddField) SQL(dialect string) []string {
	q := dialectQuote(dialect)
	col := fmt.Sprintf("ALTER TABLE %s%s%s ADD COLUMN %s%s%s %s",
		q, op.Table, q, q, op.Field.ColumnName, q, fieldSQL(op.Field, dialect))
	if !op.Field.Null {
		col += " NOT NULL"
	}
	if op.Field.Default != "" {
		col += fmt.Sprintf(" DEFAULT %s", op.Field.Default)
	}
	col += ";"
	return []string{col}
}

func (op *AddField) RollbackSQL(dialect string) []string {
	q := dialectQuote(dialect)
	return []string{fmt.Sprintf("ALTER TABLE %s%s%s DROP COLUMN %s%s%s;",
		q, op.Table, q, q, op.Field.ColumnName, q)}
}

// RemoveField drops a column.
// Equivalent to Django's migrations.RemoveField.
type RemoveField struct {
	App   string
	Model string
	Table string
	Field string
}

func (op *RemoveField) AppLabel() string  { return op.App }
func (op *RemoveField) ModelName() string { return op.Model }
func (op *RemoveField) Description() string {
	return fmt.Sprintf("Remove field %s from %s", op.Field, op.Model)
}

func (op *RemoveField) SQL(dialect string) []string {
	q := dialectQuote(dialect)
	return []string{fmt.Sprintf("ALTER TABLE %s%s%s DROP COLUMN %s%s%s;",
		q, op.Table, q, q, op.Field, q)}
}

func (op *RemoveField) RollbackSQL(_ string) []string { return nil }

// DeleteModel drops a table.
// Equivalent to Django's migrations.DeleteModel.
type DeleteModel struct {
	App   string
	Name  string
	Table string
}

func (op *DeleteModel) AppLabel() string  { return op.App }
func (op *DeleteModel) ModelName() string { return op.Name }
func (op *DeleteModel) Description() string {
	return fmt.Sprintf("Delete model %s", op.Name)
}

func (op *DeleteModel) SQL(dialect string) []string {
	q := dialectQuote(dialect)
	return []string{fmt.Sprintf("DROP TABLE IF EXISTS %s%s%s;", q, op.Table, q)}
}

func (op *DeleteModel) RollbackSQL(_ string) []string { return nil }

// RenameField renames a column.
type RenameField struct {
	App     string
	Model   string
	Table   string
	OldName string
	NewName string
	Type    string // needed for MySQL which requires the type in CHANGE COLUMN
}

func (op *RenameField) AppLabel() string  { return op.App }
func (op *RenameField) ModelName() string { return op.Model }
func (op *RenameField) Description() string {
	return fmt.Sprintf("Rename field %s to %s on %s", op.OldName, op.NewName, op.Model)
}

func (op *RenameField) SQL(dialect string) []string {
	q := dialectQuote(dialect)
	if dialect == "mysql" {
		return []string{fmt.Sprintf("ALTER TABLE %s%s%s CHANGE COLUMN %s%s%s %s%s%s %s;",
			q, op.Table, q, q, op.OldName, q, q, op.NewName, q, op.Type)}
	}
	return []string{fmt.Sprintf("ALTER TABLE %s%s%s RENAME COLUMN %s%s%s TO %s%s%s;",
		q, op.Table, q, q, op.OldName, q, q, op.NewName, q)}
}

func (op *RenameField) RollbackSQL(dialect string) []string {
	q := dialectQuote(dialect)
	if dialect == "mysql" {
		return []string{fmt.Sprintf("ALTER TABLE %s%s%s CHANGE COLUMN %s%s%s %s%s%s %s;",
			q, op.Table, q, q, op.NewName, q, q, op.OldName, q, op.Type)}
	}
	return []string{fmt.Sprintf("ALTER TABLE %s%s%s RENAME COLUMN %s%s%s TO %s%s%s;",
		q, op.Table, q, q, op.NewName, q, q, op.OldName, q)}
}

// RunSQL lets you embed raw SQL in a migration — equivalent to Django's migrations.RunSQL.
type RunSQL struct {
	App      string
	Forward  string
	Backward string
}

func (op *RunSQL) AppLabel() string    { return op.App }
func (op *RunSQL) ModelName() string   { return "" }
func (op *RunSQL) Description() string { return "Run raw SQL" }
func (op *RunSQL) SQL(_ string) []string {
	if op.Forward == "" {
		return nil
	}
	return []string{op.Forward}
}
func (op *RunSQL) RollbackSQL(_ string) []string {
	if op.Backward == "" {
		return nil
	}
	return []string{op.Backward}
}

// ---- helpers ---------------------------------------------------------------

func dialectQuote(dialect string) string {
	if dialect == "postgres" {
		return "\""
	}
	return "`"
}

func joinLines(lines []string) string {
	out := ""
	for i, l := range lines {
		if i > 0 {
			out += ",\n"
		}
		out += l
	}
	return out
}

func fieldSQL(f FieldDef, dialect string) string {
	q := dialectQuote(dialect)
	switch f.Type {
	case "AutoField":
		if dialect == "postgres" {
			return "SERIAL PRIMARY KEY"
		}
		if dialect == "sqlite3" {
			return "INTEGER PRIMARY KEY AUTOINCREMENT"
		}
		return "INT NOT NULL AUTO_INCREMENT PRIMARY KEY"
	case "BooleanField":
		return "BOOL"
	case "CharField":
		size := f.MaxSize
		if size == 0 {
			size = 255
		}
		return fmt.Sprintf("VARCHAR(%d)", size)
	case "TextField":
		return "LONGTEXT"
	case "IntegerField":
		return "INT"
	case "SmallIntegerField":
		return "SMALLINT"
	case "BigIntegerField":
		return "BIGINT"
	case "PositiveIntegerField":
		return "INT UNSIGNED"
	case "PositiveSmallIntegerField":
		return "SMALLINT UNSIGNED"
	case "PositiveBigIntegerField":
		return "BIGINT UNSIGNED"
	case "FloatField":
		return "DOUBLE PRECISION"
	case "DecimalField":
		d, dec := f.Digits, f.Decimals
		if d == 0 {
			d = 10
		}
		return fmt.Sprintf("DECIMAL(%d,%d)", d, dec)
	case "DateField":
		return "DATE"
	case "TimeField":
		return "TIME"
	case "DateTimeField":
		return "DATETIME"
	case "JSONField":
		return "JSON"
	case "ForeignKey":
		return fmt.Sprintf("INT REFERENCES %s%s%s(id)", q, f.RelTable, q)
	case "OneToOneField":
		return fmt.Sprintf("INT UNIQUE REFERENCES %s%s%s(id)", q, f.RelTable, q)
	default:
		return "TEXT"
	}
}
