package migration

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Writer generates a migration .go file from a Migration object.
// Equivalent to Django's MigrationWriter in django/db/migrations/writer.py.
//
// Django generates Python files; we generate Go files.
// The generated file is valid Go and also self-describing — it embeds
// a metadata comment block at the top that the Loader reads back.
//
// Generated file structure (mirrors Django's Migration class format):
//
//	// Code generated by djanGO. DO NOT EDIT.
//	// djanGO migration
//	// App: blog
//	// Name: 0001_initial
//	// Initial: true
//	// Dependencies: []
//	// Operations: CreateModel:Post
//	package migrations
//
//	import "github.com/mqnifestkelvin/djanGO/core/migration"
//
//	var Migration = &migration.Migration{
//	    Name: "0001_initial",
//	    App:  "blog",
//	    ...
//	}
type Writer struct {
	Migration *Migration
}

// AsString returns the complete content of the migration .go file.
// Equivalent to Django's MigrationWriter.as_string().
func (w *Writer) AsString() string {
	m := w.Migration
	var b strings.Builder

	// Header comment — mirrors Django's "Generated by Django X.Y on TIMESTAMP"
	b.WriteString(fmt.Sprintf("// Code generated by djanGO on %s. DO NOT EDIT.\n",
		time.Now().Format("2006-01-02 15:04")))
	b.WriteString("//\n")
	b.WriteString("// djanGO migration\n")
	b.WriteString(fmt.Sprintf("// App: %s\n", m.App))
	b.WriteString(fmt.Sprintf("// Name: %s\n", m.Name))
	if m.Initial {
		b.WriteString("// Initial: true\n")
	}

	// Dependencies — mirrors Django's dependencies = [("app", "name"), ...]
	if len(m.Dependencies) == 0 {
		b.WriteString("// Dependencies: []\n")
	} else {
		deps := make([]string, 0, len(m.Dependencies))
		for _, d := range m.Dependencies {
			deps = append(deps, d[0]+":"+d[1])
		}
		b.WriteString(fmt.Sprintf("// Dependencies: [%s]\n", strings.Join(deps, ", ")))
	}

	// Operation summary line (for quick grep) — e.g. "CreateModel:Post, AddField:Post"
	opSummary := make([]string, 0, len(m.Operations))
	for _, op := range m.Operations {
		typeName := fmt.Sprintf("%T", op)
		// Strip "*migration." prefix → just "CreateModel"
		if idx := strings.LastIndex(typeName, "."); idx >= 0 {
			typeName = typeName[idx+1:]
		}
		opSummary = append(opSummary, fmt.Sprintf("%s:%s", typeName, op.ModelName()))
	}
	b.WriteString(fmt.Sprintf("// Operations: %s\n", strings.Join(opSummary, ", ")))
	b.WriteString("\n")

	b.WriteString(fmt.Sprintf("package migrations\n\n"))
	b.WriteString("import \"github.com/mqnifestkelvin/djanGO/core/migration\"\n\n")

	// Migration variable — mirrors Django's class Migration(migrations.Migration)
	b.WriteString(fmt.Sprintf("// %s\n", describeOperations(m.Operations)))
	b.WriteString("var Migration = &migration.Migration{\n")
	b.WriteString(fmt.Sprintf("\tName:    %q,\n", m.Name))
	b.WriteString(fmt.Sprintf("\tApp:     %q,\n", m.App))

	if m.Initial {
		b.WriteString("\tInitial: true,\n")
	}

	// Dependencies
	b.WriteString("\tDependencies: [][2]string{\n")
	for _, d := range m.Dependencies {
		b.WriteString(fmt.Sprintf("\t\t{%q, %q},\n", d[0], d[1]))
	}
	b.WriteString("\t},\n")

	// Operations — each one serialized as a Go struct literal
	b.WriteString("\tOperations: []migration.Operation{\n")
	for _, op := range m.Operations {
		b.WriteString(serializeOperation(op))
	}
	b.WriteString("\t},\n")

	b.WriteString("}\n\n")

	// init() registers the migration with the global registry so that
	// `go run manage.go migrate` can discover it without file I/O.
	// This mirrors Django's MigrationLoader importing each migration module.
	b.WriteString("func init() {\n")
	b.WriteString("\tmigration.RegisterMigration(Migration)\n")
	b.WriteString("}\n")

	return b.String()
}

// Filename returns the file name for this migration e.g. "0001_initial.go".
// Equivalent to Django's MigrationWriter.filename.
func (w *Writer) Filename() string {
	return w.Migration.Name + ".go"
}

// Write writes the migration file to the given migrations directory.
// Equivalent to Django's MigrationWriter writing to self.path.
func (w *Writer) Write(migrationsDir string) (string, error) {
	if err := os.MkdirAll(migrationsDir, 0755); err != nil {
		return "", fmt.Errorf("migration: could not create migrations dir: %w", err)
	}

	path := filepath.Join(migrationsDir, w.Filename())
	if err := os.WriteFile(path, []byte(w.AsString()), 0644); err != nil {
		return "", fmt.Errorf("migration: could not write %s: %w", path, err)
	}
	return path, nil
}

// NextMigrationName returns the next numbered migration name.
// e.g. latestNum=0 → "0001_initial", latestNum=2 → "0003_<slug>"
func NextMigrationName(latestNum int, ops []Operation) string {
	num := fmt.Sprintf("%04d", latestNum+1)
	slug := suggestSlug(ops)
	return num + "_" + slug
}

// suggestSlug picks a descriptive slug from the operations list.
// Mirrors Django's Migration.suggest_name().
func suggestSlug(ops []Operation) string {
	if len(ops) == 0 {
		return "auto"
	}

	// Initial migration: all creates → "initial"
	allCreate := true
	for _, op := range ops {
		if _, ok := op.(*CreateModel); !ok {
			allCreate = false
			break
		}
	}
	if allCreate {
		return "initial"
	}

	// Single operation: use its description
	if len(ops) == 1 {
		op := ops[0]
		switch o := op.(type) {
		case *CreateModel:
			return "create_model_" + strings.ToLower(o.Name)
		case *AddField:
			return "add_field_" + strings.ToLower(o.Model) + "_" + strings.ToLower(o.Field.Name)
		case *RemoveField:
			return "remove_field_" + strings.ToLower(o.Model) + "_" + strings.ToLower(o.Field)
		case *DeleteModel:
			return "delete_model_" + strings.ToLower(o.Name)
		case *RenameField:
			return "rename_" + strings.ToLower(o.OldName) + "_" + strings.ToLower(o.Model)
		}
	}

	return "auto_" + time.Now().Format("20060102_150405")
}

func describeOperations(ops []Operation) string {
	if len(ops) == 0 {
		return "No operations"
	}
	descs := make([]string, 0, len(ops))
	for _, op := range ops {
		descs = append(descs, op.Description())
	}
	return strings.Join(descs, "; ")
}

// serializeOperation produces the Go struct literal for one Operation.
// This is the Go equivalent of Django's OperationWriter.
func serializeOperation(op Operation) string {
	var b strings.Builder
	switch o := op.(type) {
	case *CreateModel:
		b.WriteString("\t\t&migration.CreateModel{\n")
		b.WriteString(fmt.Sprintf("\t\t\tApp:   %q,\n", o.App))
		b.WriteString(fmt.Sprintf("\t\t\tName:  %q,\n", o.Name))
		b.WriteString(fmt.Sprintf("\t\t\tTable: %q,\n", o.Table))
		b.WriteString("\t\t\tFields: []migration.FieldDef{\n")
		for _, f := range o.Fields {
			b.WriteString(serializeFieldDef(f))
		}
		b.WriteString("\t\t\t},\n")
		b.WriteString("\t\t},\n")

	case *AddField:
		b.WriteString("\t\t&migration.AddField{\n")
		b.WriteString(fmt.Sprintf("\t\t\tApp:   %q,\n", o.App))
		b.WriteString(fmt.Sprintf("\t\t\tModel: %q,\n", o.Model))
		b.WriteString(fmt.Sprintf("\t\t\tTable: %q,\n", o.Table))
		b.WriteString("\t\t\tField: " + serializeFieldDefInline(o.Field) + ",\n")
		b.WriteString("\t\t},\n")

	case *RemoveField:
		b.WriteString("\t\t&migration.RemoveField{\n")
		b.WriteString(fmt.Sprintf("\t\t\tApp:   %q,\n", o.App))
		b.WriteString(fmt.Sprintf("\t\t\tModel: %q,\n", o.Model))
		b.WriteString(fmt.Sprintf("\t\t\tTable: %q,\n", o.Table))
		b.WriteString(fmt.Sprintf("\t\t\tField: %q,\n", o.Field))
		b.WriteString("\t\t},\n")

	case *DeleteModel:
		b.WriteString("\t\t&migration.DeleteModel{\n")
		b.WriteString(fmt.Sprintf("\t\t\tApp:   %q,\n", o.App))
		b.WriteString(fmt.Sprintf("\t\t\tName:  %q,\n", o.Name))
		b.WriteString(fmt.Sprintf("\t\t\tTable: %q,\n", o.Table))
		b.WriteString("\t\t},\n")

	case *RenameField:
		b.WriteString("\t\t&migration.RenameField{\n")
		b.WriteString(fmt.Sprintf("\t\t\tApp:     %q,\n", o.App))
		b.WriteString(fmt.Sprintf("\t\t\tModel:   %q,\n", o.Model))
		b.WriteString(fmt.Sprintf("\t\t\tTable:   %q,\n", o.Table))
		b.WriteString(fmt.Sprintf("\t\t\tOldName: %q,\n", o.OldName))
		b.WriteString(fmt.Sprintf("\t\t\tNewName: %q,\n", o.NewName))
		b.WriteString(fmt.Sprintf("\t\t\tType:    %q,\n", o.Type))
		b.WriteString("\t\t},\n")

	case *RunSQL:
		b.WriteString("\t\t&migration.RunSQL{\n")
		b.WriteString(fmt.Sprintf("\t\t\tApp:      %q,\n", o.App))
		b.WriteString(fmt.Sprintf("\t\t\tForward:  %q,\n", o.Forward))
		b.WriteString(fmt.Sprintf("\t\t\tBackward: %q,\n", o.Backward))
		b.WriteString("\t\t},\n")
	}
	return b.String()
}

// serializeFieldDef produces a clean, Django-style field definition.
// Only non-zero/non-default values are written — mirrors Django's field
// tuple format: ("field_name", models.FieldType(option=value, ...))
func serializeFieldDef(f FieldDef) string {
	var b strings.Builder
	b.WriteString("\t\t\t\tmigration.FieldDef{\n")
	b.WriteString(fmt.Sprintf("\t\t\t\t\tName:       %q,\n", f.Name))
	b.WriteString(fmt.Sprintf("\t\t\t\t\tColumnName: %q,\n", f.ColumnName))
	b.WriteString(fmt.Sprintf("\t\t\t\t\tType:       %q,\n", f.Type))

	// Only emit optional attributes when they differ from the zero value
	if f.MaxSize > 0 {
		b.WriteString(fmt.Sprintf("\t\t\t\t\tMaxSize:    %d,\n", f.MaxSize))
	}
	if f.Null {
		b.WriteString("\t\t\t\t\tNull:       true,\n")
	}
	if f.Blank {
		b.WriteString("\t\t\t\t\tBlank:      true,\n")
	}
	if f.Unique {
		b.WriteString("\t\t\t\t\tUnique:     true,\n")
	}
	if f.PrimaryKey {
		b.WriteString("\t\t\t\t\tPrimaryKey: true,\n")
	}
	if f.AutoIncr {
		b.WriteString("\t\t\t\t\tAutoIncr:   true,\n")
	}
	if f.Index {
		b.WriteString("\t\t\t\t\tIndex:      true,\n")
	}
	if f.Default != "" {
		b.WriteString(fmt.Sprintf("\t\t\t\t\tDefault:    %q,\n", f.Default))
	}
	if f.Digits > 0 {
		b.WriteString(fmt.Sprintf("\t\t\t\t\tDigits:     %d,\n", f.Digits))
	}
	if f.Decimals > 0 {
		b.WriteString(fmt.Sprintf("\t\t\t\t\tDecimals:   %d,\n", f.Decimals))
	}
	if f.RelTable != "" {
		b.WriteString(fmt.Sprintf("\t\t\t\t\tRelTable:   %q,\n", f.RelTable))
	}
	b.WriteString("\t\t\t\t},\n")
	return b.String()
}

func serializeFieldDefInline(f FieldDef) string {
	// Used by AddField — still compact but shows all values
	return fmt.Sprintf(
		"migration.FieldDef{Name:%q, ColumnName:%q, Type:%q, MaxSize:%d, Null:%v, Unique:%v, PrimaryKey:%v, AutoIncr:%v, Default:%q}",
		f.Name, f.ColumnName, f.Type, f.MaxSize, f.Null, f.Unique, f.PrimaryKey, f.AutoIncr, f.Default,
	)
}
