package management

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

func RunStartProject(args []string) {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "Error: you must provide a project name.")
		fmt.Fprintln(os.Stderr, "Usage: djangocli startproject <name> [directory]")
		os.Exit(1)
	}

	name := args[0]
	var target string
	if len(args) >= 2 {
		target = args[1]
	}

	if err := validateName(name); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		os.Exit(1)
	}

	topDir := resolveTargetDir(name, target)

	if err := os.MkdirAll(topDir, 0755); err != nil {
		if os.IsExist(err) {
			fmt.Fprintf(os.Stderr, "Error: '%s' already exists.\n", topDir)
		} else {
			fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		}
		os.Exit(1)
	}

	secretKey := generateSecretKey()

	if err := scaffoldProject(topDir, name, secretKey); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		os.Exit(1)
	}

}

func validateName(name string) error {
	if name == "" {
		return fmt.Errorf("project name cannot be empty")
	}
	for i, r := range name {
		if i == 0 && !unicode.IsLetter(r) && r != '_' {
			return fmt.Errorf("'%s' is not a valid project name: must start with a letter or underscore", name)
		}
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) && r != '_' {
			return fmt.Errorf("'%s' is not a valid project name: only letters, digits, and underscores allowed", name)
		}
	}
	return nil
}

func resolveTargetDir(name, target string) string {
	if target == "" {
		cwd, _ := os.Getwd()
		return filepath.Join(cwd, name)
	}
	abs, _ := filepath.Abs(target)
	return abs
}

func generateSecretKey() string {
	b := make([]byte, 32)
	rand.Read(b)
	return "djangosecretkey-" + hex.EncodeToString(b)
}

func toCamelCase(name string) string {
	parts := strings.Split(name, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func scaffoldProject(topDir, name, secretKey string) error {
	// Django generates exactly 6 files:
	// manage.py  (root)
	// <name>/__init__.py
	// <name>/settings.py
	// <name>/urls.py
	// <name>/wsgi.py
	// <name>/asgi.py
	//
	// We mirror this exactly — no extras, no directories beyond what Django creates.
	cfg := name

	files := map[string]func() string{
		// Root — mirrors Django's manage.py
		"manage.go": func() string {
			return fmt.Sprintf(`package main

import (
	"os"

	"github.com/mqnifestkelvin/djanGO/core/management"

	// Import your apps here so their init() registers models, routes and commands.
	// Example:
	//   _ "%s/blog"

	_ "github.com/mqnifestkelvin/djanGO/core/management/commands"
)

func main() {
	management.Execute(os.Args[1:])
}
`, name)
		},

		// go.mod — Go equivalent of requirements, no Django counterpart but necessary
		"go.mod": func() string {
			return fmt.Sprintf(`module %s

go 1.21

require (
	github.com/mqnifestkelvin/djanGO v0.1.0
)
`, name)
		},

		// Inner config package — mirrors Django's inner <project_name>/ folder

		// mirrors __init__.py — empty package declaration
		cfg + "/init.go": func() string {
			return fmt.Sprintf(`package %s
`, name)
		},

		// mirrors settings.py — full boilerplate matching Django's generated settings
		cfg + "/settings.go": func() string {
			return fmt.Sprintf(`package %s

// djanGO settings for %s project.
// Generated by 'djanGO-admin startproject' using djanGO v0.1.0.
//
// For the full list of settings and their values, see
// https://github.com/mqnifestkelvin/djanGO

import (
	"path/filepath"

	"github.com/mqnifestkelvin/djanGO/conf"
)

// BaseDir is the root of the project — equivalent to Django's BASE_DIR.
// Build paths inside the project like: filepath.Join(BaseDir, "subdir")
var BaseDir = func() string {
	return filepath.Join("..")
}()

// SECURITY WARNING: keep the secret key used in production secret!
var SecretKey = "%s"

// SECURITY WARNING: don't run with debug turned on in production!
var Debug = true

var AllowedHosts = []string{}

// Application definition — add your apps here, then run makemigrations.
var InstalledApps = []string{
	"djanGO.contrib.admin",
	"djanGO.contrib.auth",
	"djanGO.contrib.contenttypes",
	"djanGO.contrib.sessions",
	"djanGO.contrib.messages",
	"djanGO.contrib.staticfiles",
}

var Middleware = []string{
	"djanGO.middleware.security.SecurityMiddleware",
	"djanGO.contrib.sessions.middleware.SessionMiddleware",
	"djanGO.middleware.common.CommonMiddleware",
	"djanGO.middleware.csrf.CsrfViewMiddleware",
	"djanGO.contrib.auth.middleware.AuthenticationMiddleware",
	"djanGO.contrib.messages.middleware.MessageMiddleware",
	"djanGO.middleware.clickjacking.XFrameOptionsMiddleware",
}

var RootURLConf = "%s.urls"

var Templates = []map[string]interface{}{
	{
		"BACKEND": "djanGO.template.backends.DjangoTemplates",
		"DIRS":    []string{},
		"APP_DIRS": true,
		"OPTIONS": map[string]interface{}{
			"context_processors": []string{
				"djanGO.template.context_processors.request",
				"djanGO.contrib.auth.context_processors.auth",
				"djanGO.contrib.messages.context_processors.messages",
			},
		},
	},
}

var WSGIApplication = "%s.wsgi.Application"

// Database
// https://github.com/mqnifestkelvin/djanGO#databases
var Databases = map[string]map[string]string{
	"default": {
		"ENGINE": "sqlite3",
		"NAME":   filepath.Join(BaseDir, "db.sqlite3"),
	},
}

// Password validation
var AuthPasswordValidators = []map[string]string{
	{"NAME": "djanGO.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
	{"NAME": "djanGO.contrib.auth.password_validation.MinimumLengthValidator"},
	{"NAME": "djanGO.contrib.auth.password_validation.CommonPasswordValidator"},
	{"NAME": "djanGO.contrib.auth.password_validation.NumericPasswordValidator"},
}

// Internationalization
var LanguageCode = "en-us"
var TimeZone = "UTC"
var UseI18N = true
var UseTZ = true

// Static files (CSS, JavaScript, Images)
var StaticURL = "static/"

// Email
var Mailers = map[string]map[string]string{
	"default": {
		"BACKEND": "djanGO.core.mail.backends.ConsoleEmailBackend",
	},
}

func init() {
	conf.Configure(conf.Settings{
		InstalledApps: InstalledApps,
		Debug:         Debug,
		SecretKey:     SecretKey,
		AllowedHosts:  AllowedHosts,
		Databases:     Databases,
		StaticURL:     StaticURL,
		TimeZone:      TimeZone,
		LanguageCode:  LanguageCode,
	})
}
`, name, name, secretKey, name, name)
		},

		// mirrors urls.py — boilerplate with admin route and examples
		cfg + "/urls.go": func() string {
			return fmt.Sprintf(`package %s

import "github.com/mqnifestkelvin/djanGO/core/urls"

// URL configuration for %s project.
//
// The urlpatterns list routes URLs to views. For more information please see:
//   https://github.com/mqnifestkelvin/djanGO#url-routing
//
// Examples:
//   urls.Path("/", views.HomeView, "home")
//   urls.Include("/blog/", blog.URLPatterns)

var URLPatterns = urls.Patterns(
// urls.Path("/admin/", admin.AdminSite.URLs),
)
`, name, name)
		},

		// mirrors wsgi.py — functional boilerplate
		cfg + "/wsgi.go": func() string {
			return fmt.Sprintf(`package %s

// WSGI config for %s project.
//
// It exposes the WSGI callable as a package-level variable named Application.
//
// For more information on this file, see
// https://github.com/mqnifestkelvin/djanGO#deployment

import (
	"os"

	"github.com/mqnifestkelvin/djanGO/server/web"
)

func init() {
	os.Setenv("DJANGO_SETTINGS_MODULE", "%s.settings")
}

// Application is the WSGI-compatible entry point.
var Application = web.BeeApp
`, name, name, name)
		},

		// mirrors asgi.py — functional boilerplate
		cfg + "/asgi.go": func() string {
			return fmt.Sprintf(`package %s

// ASGI config for %s project.
//
// It exposes the ASGI callable as a package-level variable named Application.
//
// For more information on this file, see
// https://github.com/mqnifestkelvin/djanGO#deployment

import (
	"os"

	"github.com/mqnifestkelvin/djanGO/server/web"
)

func init() {
	os.Setenv("DJANGO_SETTINGS_MODULE", "%s.settings")
}

// Application is the ASGI-compatible entry point for async deployment.
var Application = web.BeeApp
`, name, name, name)
		},
	}

	for relPath, contentFn := range files {
		fullPath := filepath.Join(topDir, filepath.FromSlash(relPath))

		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			return fmt.Errorf("could not create directory for %s: %w", relPath, err)
		}

		if err := os.WriteFile(fullPath, []byte(contentFn()), 0644); err != nil {
			return fmt.Errorf("could not write %s: %w", relPath, err)
		}
	}

	return nil
}
