package management

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

func RunStartProject(args []string) {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "Error: you must provide a project name.")
		fmt.Fprintln(os.Stderr, "Usage: djangocli startproject <name> [directory]")
		os.Exit(1)
	}

	name := args[0]
	var target string
	if len(args) >= 2 {
		target = args[1]
	}

	if err := validateName(name); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		os.Exit(1)
	}

	topDir := resolveTargetDir(name, target)

	if err := os.MkdirAll(topDir, 0755); err != nil {
		if os.IsExist(err) {
			fmt.Fprintf(os.Stderr, "Error: '%s' already exists.\n", topDir)
		} else {
			fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		}
		os.Exit(1)
	}

	secretKey := generateSecretKey()

	if err := scaffoldProject(topDir, name, secretKey); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		os.Exit(1)
	}

}

func validateName(name string) error {
	if name == "" {
		return fmt.Errorf("project name cannot be empty")
	}
	for i, r := range name {
		if i == 0 && !unicode.IsLetter(r) && r != '_' {
			return fmt.Errorf("'%s' is not a valid project name: must start with a letter or underscore", name)
		}
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) && r != '_' {
			return fmt.Errorf("'%s' is not a valid project name: only letters, digits, and underscores allowed", name)
		}
	}
	return nil
}

func resolveTargetDir(name, target string) string {
	if target == "" {
		cwd, _ := os.Getwd()
		return filepath.Join(cwd, name)
	}
	abs, _ := filepath.Abs(target)
	return abs
}

func generateSecretKey() string {
	b := make([]byte, 32)
	rand.Read(b)
	return "djangosecretkey-" + hex.EncodeToString(b)
}

func toCamelCase(name string) string {
	parts := strings.Split(name, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func scaffoldProject(topDir, name, secretKey string) error {
	// Django generates exactly 6 files:
	// manage.py  (root)
	// <name>/__init__.py
	// <name>/settings.py
	// <name>/urls.py
	// <name>/wsgi.py
	// <name>/asgi.py
	//
	// We mirror this exactly — no extras, no directories beyond what Django creates.
	cfg := name

	files := map[string]func() string{
		// Root — mirrors Django's manage.py
		"manage.go": func() string {
			return fmt.Sprintf(`package main

import (
	"os"

	"github.com/mqnifestkelvin/djanGO/core/management"

	// Import your apps here so their init() registers models, routes and commands.
	// Example:
	//   _ "%s/blog"

	_ "github.com/mqnifestkelvin/djanGO/core/management/commands"
)

func main() {
	management.Execute(os.Args[1:])
}
`, name)
		},

		// go.mod — Go equivalent of requirements, no Django counterpart but necessary
		"go.mod": func() string {
			return fmt.Sprintf(`module %s

go 1.21

require (
	github.com/mqnifestkelvin/djanGO v0.1.0
)
`, name)
		},

		// Inner config package — mirrors Django's inner <project_name>/ folder

		// mirrors __init__.py
		cfg + "/init.go": func() string {
			return fmt.Sprintf("package %s\n", name)
		},

		// mirrors settings.py
		cfg + "/settings.go": func() string {
			return fmt.Sprintf(`package %s

// djanGO settings for %s project.
// Generated by 'djanGO-admin startproject'.

var (
	SecretKey = "%s"
	Debug     = true

	AllowedHosts = []string{}

	InstalledApps = []string{
		"djanGO.contrib.admin",
		"djanGO.contrib.auth",
		"djanGO.contrib.contenttypes",
		"djanGO.contrib.sessions",
		"djanGO.contrib.staticfiles",
	}

	Middleware = []string{
		"djanGO.middleware.security.SecurityMiddleware",
		"djanGO.contrib.sessions.middleware.SessionMiddleware",
		"djanGO.middleware.common.CommonMiddleware",
		"djanGO.middleware.csrf.CsrfViewMiddleware",
		"djanGO.contrib.auth.middleware.AuthenticationMiddleware",
		"djanGO.middleware.clickjacking.XFrameOptionsMiddleware",
	}

	RootURLConf = "%s.urls"

	Databases = map[string]map[string]string{
		"default": {
			"ENGINE": "sqlite3",
			"NAME":   "db.sqlite3",
		},
	}

	LanguageCode = "en-us"
	TimeZone     = "UTC"
	UseI18N      = true
	UseTZ        = true

	StaticURL = "static/"
)
`, name, name, secretKey, name)
		},

		// mirrors urls.py
		cfg + "/urls.go": func() string {
			return fmt.Sprintf(`package %s

import "github.com/mqnifestkelvin/djanGO/server/web"

// URL configuration for %s project.
//
// Examples:
//   web.Router("/", &views.HomeController{})
//   web.Router("/blog/", &blog.IndexController{})
var URLPatterns = func() {
	_ = web.BeeApp
	// web.Router("/admin/", &admin.AdminController{})
}
`, name, name)
		},

		// mirrors wsgi.py
		cfg + "/wsgi.go": func() string {
			return fmt.Sprintf(`package %s

// WSGI config for %s project.
// Used for production deployment behind a reverse proxy.
`, name, name)
		},

		// mirrors asgi.py
		cfg + "/asgi.go": func() string {
			return fmt.Sprintf(`package %s

// ASGI config for %s project.
// Used for async/websocket production deployment.
`, name, name)
		},
	}

	for relPath, contentFn := range files {
		fullPath := filepath.Join(topDir, filepath.FromSlash(relPath))

		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			return fmt.Errorf("could not create directory for %s: %w", relPath, err)
		}

		if err := os.WriteFile(fullPath, []byte(contentFn()), 0644); err != nil {
			return fmt.Errorf("could not write %s: %w", relPath, err)
		}
	}

	return nil
}
